# -*- coding: utf-8 -*-
"""Simulação de Uso de Energias Renováveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9lSx2QVNwDdpQLMziKtQs-4L0mK6xHi

# Simulação de Uso de Energias Renováveis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_geracao = pd.read_csv('/content/geracao_solar.csv')

"""## Simulação On-Grid - Casa

"""

df_casa = pd.read_csv('/content/consumo_casa.csv')

df_casa['Geracao_kWh'] = df_geracao['Geracao_kWh']

df_casa['Usado_do_Solar'] = np.minimum(
    df_casa['Consumo_kWh'],
    df_casa['Geracao_kWh']
)

df_casa['Injetado_na_Rede'] = np.where(
    df_casa['Geracao_kWh'] > df_casa['Consumo_kWh'],
    df_casa['Geracao_kWh'] - df_casa['Consumo_kWh'],
    0
)

df_casa['Usado_da_Rede'] = np.where(
    df_casa['Consumo_kWh'] > df_casa['Geracao_kWh'],
    df_casa['Consumo_kWh'] - df_casa['Geracao_kWh'],
    0
)

df_casa.head()

"""### Calculos"""

#custo e economia
tarifa = 0.90  # R$/kWh

df_casa['Custo_sem_Solar'] = df_casa['Consumo_kWh'] * tarifa
df_casa['Custo_com_Solar'] = df_casa['Usado_da_Rede'] * tarifa
df_casa['Economia_R$'] = df_casa['Custo_sem_Solar'] - df_casa['Custo_com_Solar']

df_casa.head()

# CO₂ evitado
fator_co2 = 0.084  # kg de CO2 por kWh
df_casa['CO2_Evitado_kg'] = df_casa['Usado_do_Solar'] * fator_co2

df_casa.head()

df_casa['Perc_Fotovoltaico_%'] = (df_casa['Usado_do_Solar'] / df_casa['Consumo_kWh']) * 100

df_casa.head()

total_consumo_casa = df_casa['Consumo_kWh'].sum()
total_geracao_casa = df_casa['Geracao_kWh'].sum()
total_economia_casa = df_casa['Economia_R$'].sum()
total_co2_casa = df_casa['CO2_Evitado_kg'].sum()

perc_fv_casa = (
    df_casa['Usado_do_Solar'].sum() / df_casa['Consumo_kWh'].sum()
) * 100

print(f"Consumo anual da casa: {total_consumo_casa:.2f} kWh")
print(f"Geração anual da casa: {total_geracao_casa:.2f} kWh")
print(f"Economia anual da casa: R$ {total_economia_casa:.2f}")
print(f"CO2 evitado no ano: {total_co2_casa:.2f} kg")
print(f"Cobertura fotovoltaica: {perc_fv_casa:.2f}%")

"""### Gráficos

"""

plt.figure()
plt.plot(df_casa['Mes'], df_casa['Consumo_kWh'], label='Consumo')
plt.plot(df_casa['Mes'], df_casa['Geracao_kWh'], label='Geração Solar')
plt.xticks(rotation=45)
plt.title('Casa - Consumo x Geração Fotovoltaica On-Grid')
plt.ylabel('kWh')
plt.legend()
plt.show()

plt.figure()
plt.plot(df_casa['Mes'], df_casa['Perc_Fotovoltaico_%'])
plt.xticks(rotation=45)
plt.title('Percentual de Cobertura Fotovoltaica - Casa')
plt.ylabel('%')
plt.ylim(0, 110)
plt.show()

"""### Histograma"""

plt.figure()
sns.histplot(df_casa['Economia_R$'], kde=True)
plt.title('Distribuição da Economia Mensal - Casa')
plt.xlabel('Economia (R$)')
plt.show()

"""## Simulação On-Grid - Empresa

"""

df_consumo_empresa = pd.read_csv('/content/consumo_empresa.csv')

df_empresa = df_consumo_empresa.copy()
df_empresa['Geracao_kWh'] = df_geracao['Geracao_kWh']

df_empresa['Usado_do_Solar'] = np.minimum(
    df_empresa['Consumo_kWh'],
    df_empresa['Geracao_kWh']
)

df_empresa['Injetado_na_Rede'] = np.where(
    df_empresa['Geracao_kWh'] > df_empresa['Consumo_kWh'],
    df_empresa['Geracao_kWh'] - df_empresa['Consumo_kWh'],
    0
)

df_empresa['Usado_da_Rede'] = np.where(
    df_empresa['Consumo_kWh'] > df_empresa['Geracao_kWh'],
    df_empresa['Consumo_kWh'] - df_empresa['Geracao_kWh'],
    0
)

df_empresa.head()

"""### Calculos"""

# custo e economia
tarifa = 0.90  # R$/kWh

df_empresa['Custo_sem_Solar'] = df_empresa['Consumo_kWh'] * tarifa
df_empresa['Custo_com_Solar'] = df_empresa['Usado_da_Rede'] * tarifa
df_empresa['Economia_R$'] = df_empresa['Custo_sem_Solar'] - df_empresa['Custo_com_Solar']

df_empresa.head()

# CO₂ evitado
fator_co2 = 0.084  # kg de CO2 por kWh
df_empresa['CO2_Evitado_kg'] = df_empresa['Usado_do_Solar'] * fator_co2

df_empresa.head()

df_empresa['Perc_Fotovoltaico_%'] = (df_empresa['Usado_do_Solar'] / df_empresa['Consumo_kWh']) * 100

df_empresa.head()

total_consumo_empresa = df_empresa['Consumo_kWh'].sum()
total_geracao_empresa = df_empresa['Geracao_kWh'].sum()
total_economia_empresa = df_empresa['Economia_R$'].sum()
total_co2_empresa = df_empresa['CO2_Evitado_kg'].sum()

perc_fv_empresa = (df_empresa['Usado_do_Solar'].sum() / df_empresa['Consumo_kWh'].sum()) * 100

print(f"Consumo anual da empresa: {total_consumo_empresa:.2f} kWh")
print(f"Geração anual da empresa: {total_geracao_empresa:.2f} kWh")
print(f"Economia anual da empresa: R$ {total_economia_empresa:.2f}")
print(f"CO2 evitado no ano: {total_co2_empresa:.2f} kg")
print(f"Cobertura fotovoltaica: {perc_fv_empresa:.2f}%")

"""### Gráficos"""

plt.figure()
plt.plot(df_empresa['Mes'], df_empresa['Consumo_kWh'], label='Consumo')
plt.plot(df_empresa['Mes'], df_empresa['Geracao_kWh'], label='Geração Solar')
plt.xticks(rotation=45)
plt.title('Empresa - Consumo x Geração Fotovoltaica On-Grid')
plt.ylabel('kWh')
plt.legend()
plt.show()

plt.figure()
plt.plot(df_empresa['Mes'], df_empresa['Perc_Fotovoltaico_%'])
plt.xticks(rotation=45)
plt.title('Percentual de Cobertura Fotovoltaica - Empresa')
plt.ylabel('%')
plt.show()

"""### Histograma

"""

plt.figure()
sns.histplot(df_empresa['Economia_R$'], kde=True)
plt.title('Distribuição da Economia Mensal - Empresa')
plt.xlabel('Economia (R$)')
plt.show()